### ISSUE TITLE
Add discord id/username text entry question

### ISSUE THREAD

**Issue by heratyian** [DPI-WE/join-the-chat#2]

**Comment by armstrca** [comment]
Happy to do this one, but I'd need repo permissions. Also it seems like text entry stuff is not happening inside the repo? For example, [the GitHub setup lesson](https://github.com/DPI-WE/setup-github-profile/blob/main/content.md) has text entry stuff on Firstdraft, but not in `content.md` or elsewhere in that repo. Where does that happen?

**Comment by heratyian** [comment]
We'll be able to collect this information later if we have a text entry question in content.md

**Comment by armstrca** [comment]
Can you give me repo permissions on this?

**Comment by heratyian** [comment]
> Can you give me repo permissions on this?

try now
